version: '3.8'

services:
  cake_db:
    container_name: postgres_container
    image: michaelplug/cake_db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - "5430:5432"
    network_mode: "cake-network"
    volumes:
    - ./data:/var/lib/postgresql/data
    # copy the sql script to create tables
    #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_db.sql
    #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_schema.sql
    - ./sql/create_status_enum.sql:/docker-entrypoint-initdb.d/.sql
    - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    - ./sql/create_functions.sql:/docker-entrypoint-initdb.d/.sql
    - ./sql/create_triggers.sql:/docker-entrypoint-initdb.d/create_triggers.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    network_mode: "cake-network"